/*
 * Copyright 2026 QRun.IO, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Maps Material Icons names (as declared in QQQ `QIcon` metadata) to Lucide icon components.
 */

import {
  Accessibility, Activity, AlarmClock, Archive, ArrowDown, ArrowUp, AtSign, Award, Ban, Barcode, ChartBar,
  ChartLine, ChartPie, Bell, BellRing, Blocks, BookOpen, Bookmark, Box, Boxes, Briefcase, Bug, Building2,
  Calculator, Calendar, CalendarClock, CalendarDays, Camera, Car, CircleCheck, CircleHelp, CirclePlay,
  CircleUser, CircleX, Clipboard, ClipboardList, Clock, Cloud, CloudUpload, Code, Coffee, Cog, Contact, Copy,
  CreditCard, Database, DollarSign, Download, Earth, Eye, EyeOff, Factory, FileCog, FilePen, FilePlus,
  FileSpreadsheet, FileText, FileUp, Filter, Flag, FlaskConical, Folder, FolderInput, FolderOpen, FolderUp,
  Forklift, Gamepad2, Gavel, Gift, GitMerge, Globe, GraduationCap, Grid3x3, Hand, Handshake, HardDrive, Heart,
  HeartPulse, History, Hourglass, House, IdCard, Image, Inbox, Info, Key, Keyboard, LayoutDashboard,
  LayoutGrid, LayoutList, Layers, Leaf, Library, Lightbulb, Link, List, ListChecks, ListOrdered, Lock,
  LockOpen, Mail, Map, MapPin, Megaphone, MessageSquare, Minus, Monitor, Network, Newspaper, NotebookPen,
  Package, PackageOpen, PawPrint, Pencil, Percent, PersonStanding, Phone, PiggyBank, Pill, Plane, Play,
  Plug, Plus, Power, Printer, Puzzle, QrCode, Receipt, RefreshCw, Repeat, Rocket, Route, Save, Scale,
  School, Search, Send, Server, Settings, Share2, Shield, ShieldCheck, ShoppingCart, SlidersHorizontal,
  Smile, SquareStack, Star, Sparkles, Stethoscope, Store, Table, Table2, Tag, Tags, Terminal, TextCursorInput,
  ThumbsUp, Timer, TrafficCone, Trash2, TrendingUp, Trophy, Truck, Type, Upload, User, UserCheck, UserCog,
  UserPlus, UserRound, Users, Video, Wallet, Warehouse, Webhook, Workflow, Wrench, Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Material Icons name → Lucide component. Covers the names used across QQQ, its
 * sample application and the QRun qbits, plus common general-purpose names.
 */
const MATERIAL_TO_LUCIDE: Record<string, LucideIcon> = {
  abc: Type,
  accessibility: Accessibility,
  account_box: CircleUser,
  account_circle: CircleUser,
  account_tree: Workflow,
  add: Plus,
  add_alert: BellRing,
  add_circle: Plus,
  admin_panel_settings: ShieldCheck,
  alarm: AlarmClock,
  analytics: ChartBar,
  app_registration: LayoutGrid,
  apps: LayoutGrid,
  archive: Archive,
  arrow_downward: ArrowDown,
  arrow_upward: ArrowUp,
  article: Newspaper,
  assessment: ChartBar,
  assignment: ClipboardList,
  attach_money: DollarSign,
  auto_delete: Trash2,
  badge: IdCard,
  bar_chart: ChartBar,
  biotech: FlaskConical,
  block: Ban,
  blocks: Blocks,
  book: BookOpen,
  bookmark: Bookmark,
  border_color: Pencil,
  bug_report: Bug,
  build: Wrench,
  business: Building2,
  business_center: Briefcase,
  calculate: Calculator,
  calendar_month: CalendarDays,
  calendar_today: Calendar,
  call: Phone,
  camera_alt: Camera,
  cancel: CircleX,
  category: Boxes,
  chat: MessageSquare,
  check_circle: CircleCheck,
  checklist: ListChecks,
  child_friendly: Smile,
  cloud: Cloud,
  cloud_sync: Cloud,
  cloud_upload: CloudUpload,
  code: Code,
  coffee: Coffee,
  construction: TrafficCone,
  contact_mail: Contact,
  contacts: Contact,
  content_copy: Copy,
  content_paste: Clipboard,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  data_object: Code,
  dataset: Database,
  delete: Trash2,
  description: FileText,
  developer_mode: Terminal,
  directions_car: Car,
  directions_run: PersonStanding,
  diversity_3: Users,
  dns: Server,
  done: CircleCheck,
  download: Download,
  drive_file_move: FolderInput,
  drive_folder_upload: FolderUp,
  dynamic_form: FilePen,
  edit: Pencil,
  edit_note: NotebookPen,
  electrical_services: Plug,
  email: Mail,
  emoji_events: Trophy,
  emoji_people: PersonStanding,
  error: CircleX,
  error_outline: CircleX,
  event: CalendarClock,
  explore: Map,
  extension: Puzzle,
  factory: Factory,
  favorite: Heart,
  file_copy: Copy,
  file_present: FileText,
  filter_alt: Filter,
  filter_list: Filter,
  flag: Flag,
  flaky: Activity,
  flight: Plane,
  folder: Folder,
  folder_open: FolderOpen,
  forklift: Forklift,
  game: Gamepad2,
  gavel: Gavel,
  grid_view: Grid3x3,
  group: Users,
  groups: Users,
  handshake: Handshake,
  healing: HeartPulse,
  help: CircleHelp,
  help_outline: CircleHelp,
  hidden: EyeOff,
  history: History,
  history_edu: BookOpen,
  home: House,
  horizontal_rule: Minus,
  hourglass_empty: Hourglass,
  image: Image,
  inbox: Inbox,
  info: Info,
  input: TextCursorInput,
  insert_chart: ChartBar,
  insights: TrendingUp,
  inventory: Package,
  inventory_2: PackageOpen,
  key: Key,
  keyboard: Keyboard,
  label: Tag,
  language: Globe,
  layers: Layers,
  leaderboard: ChartBar,
  library_add: Library,
  library_books: Library,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  list_alt: LayoutList,
  local_hospital: Stethoscope,
  local_offer: Tags,
  local_shipping: Truck,
  location_city: Building2,
  location_on: MapPin,
  lock: Lock,
  lock_open: LockOpen,
  mail: Mail,
  manage_accounts: UserCog,
  map: Map,
  medication: Pill,
  memory: HardDrive,
  menu_book: BookOpen,
  merge: GitMerge,
  monetization_on: DollarSign,
  monitor: Monitor,
  more_time: Timer,
  new_releases: Sparkles,
  note: NotebookPen,
  notes: NotebookPen,
  notifications: Bell,
  numbers: ListOrdered,
  outlet: Plug,
  output: Upload,
  paid: DollarSign,
  payments: Wallet,
  people: Users,
  people_alt: Users,
  percent: Percent,
  person: User,
  person_add: UserPlus,
  person_outline: UserRound,
  pets: PawPrint,
  phone: Phone,
  photo: Image,
  pie_chart: ChartPie,
  pivot_table_chart: Table2,
  play_arrow: Play,
  play_circle: CirclePlay,
  play_circle_outline: CirclePlay,
  policy: Shield,
  polyline: Network,
  power: Power,
  power_input: Plug,
  print: Printer,
  public: Earth,
  publish: Upload,
  qr_code: QrCode,
  query_stats: TrendingUp,
  quiz: CircleHelp,
  receipt: Receipt,
  receipt_long: Receipt,
  redeem: Gift,
  refresh: RefreshCw,
  reorder: ListOrdered,
  repeat: Repeat,
  rocket_launch: Rocket,
  route: Route,
  rule: ListChecks,
  save: Save,
  savings: PiggyBank,
  scale: Scale,
  schedule: Clock,
  schedule_send: Send,
  schema: Network,
  school: School,
  science: FlaskConical,
  search: Search,
  security: Shield,
  send: Send,
  settings: Settings,
  settings_applications: Cog,
  share: Share2,
  shopping_cart: ShoppingCart,
  snippet_folder: FileCog,
  sort_by_alpha: Type,
  sports: Trophy,
  star: Star,
  stars: Star,
  store: Store,
  storefront: Store,
  subscriptions: SquareStack,
  supervised_user_circle: UserCheck,
  supervisor_account: UserCheck,
  switch_account: UserCog,
  sync: RefreshCw,
  sync_lock: Lock,
  table_chart: Table,
  table_rows: Table2,
  table_view: Table,
  task: ListChecks,
  task_alt: CircleCheck,
  terminal: Terminal,
  text_fields: Type,
  text_snippet: FileText,
  thumb_up: ThumbsUp,
  timer: Timer,
  traffic: TrafficCone,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  update: RefreshCw,
  update_disabled: Ban,
  upload: Upload,
  upload_file: FileUp,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  video_library: Video,
  view_compact: LayoutGrid,
  view_list: LayoutList,
  visibility: Eye,
  visibility_off: EyeOff,
  wallet: Wallet,
  warehouse: Warehouse,
  waving_hand: Hand,
  webhook: Webhook,
  webhooks: Webhook,
  widgets: LayoutGrid,
  work: Briefcase,
  workspaces: Layers,
  campaign: Megaphone,
  local_cafe: Coffee,
  eco: Leaf,
  bolt: Zap,
  add_shopping_cart: ShoppingCart,
  note_add: FilePlus,
  grading: FileSpreadsheet,
}

/** Suffixes Material uses for style variants of the same glyph. */
const VARIANT_SUFFIX = /_(outline|outlined|rounded|sharp|two_tone|icon)$/

/**
 * Normalizes a Material Icons name: trims, lowercases, and strips a style-variant suffix
 * when the plain name is mapped (e.g. `people_outlined` → `people`).
 *
 * @param name - Material Icons name from metadata.
 * @returns The name used for lookup.
 */
export function normalizeMaterialIconName(name: string): string {
  const trimmed = name.trim().toLowerCase()
  if (MATERIAL_TO_LUCIDE[trimmed]) return trimmed
  const base = trimmed.replace(VARIANT_SUFFIX, '')
  return MATERIAL_TO_LUCIDE[base] ? base : trimmed
}

/**
 * Resolves a Material Icons name to its Lucide component.
 *
 * @param name - Material Icons name from metadata (for example `"local_shipping"`).
 * @returns The Lucide icon, or `undefined` when the name has no mapping.
 */
export function materialIconComponent(name: string | undefined | null): LucideIcon | undefined {
  if (!name) return undefined
  return MATERIAL_TO_LUCIDE[normalizeMaterialIconName(name)]
}
