/*
 * Copyright 2026 QRun.IO, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at https://www.apache.org/licenses/LICENSE-2.0
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Map;
import com.kingsrook.qqq.backend.core.context.QContext;
import com.kingsrook.qqq.backend.core.exceptions.QException;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunBackendStepInput;
import com.kingsrook.qqq.backend.core.model.actions.processes.RunBackendStepOutput;
import com.kingsrook.qqq.backend.core.model.metadata.QInstance;
import com.kingsrook.qqq.esb.api.EsbRouteProvider;
import com.kingsrook.qqq.esb.metadata.EsbOverviewWidgetMetaDataProducer;
import com.kingsrook.qqq.middleware.javalin.QJavalinMetaData;
import com.kingsrook.qqq.backend.core.model.metadata.code.QCodeReference;
import com.kingsrook.qqq.backend.core.model.metadata.processes.QBackendStepMetaData;
import com.kingsrook.qqq.backend.core.model.session.QSession;
import com.kingsrook.qqq.backend.module.rdbms.jdbc.ConnectionManager;
import com.kingsrook.qqq.esb.connection.EsbConnectionManager;
import com.kingsrook.qqq.esb.management.EsbBrokerNames;
import com.kingsrook.qqq.esb.model.EsbProcessMetaData;
import com.kingsrook.qqq.esb.model.EsbProviderType;
import com.kingsrook.qqq.esb.runtime.QEsbRuntime;
import com.kingsrook.qqq.esb.runtime.EsbTriggerState;
import com.kingsrook.qqq.esb.stats.EsbStats;
import com.kingsrook.qqq.esb.envelope.EsbEvent;
import com.kingsrook.sampleapp.metadata.SampleMetaDataProvider;
import com.kingsrook.sampleapp.processes.syncperson.SyncPersonStep;
import jakarta.jms.Message;
import jakarta.jms.MessageConsumer;
import jakarta.jms.MessageProducer;
import jakarta.jms.TemporaryQueue;
import org.apache.activemq.artemis.api.jms.management.JMSManagementHelper;
import org.apache.activemq.artemis.api.core.management.ResourceNames;
import jakarta.jms.Session;


/*******************************************************************************
 ** Uses the sample's real broker, publication, runtime and subscriber. Only the
 ** application step is augmented: record its effect in owned H2 and allow a
 ** controlled application failure to exercise real dead-lettering and replay.
 *******************************************************************************/
public class EsbFixtures
{
   private static final String PROVIDER = "sampleArtemis";
   private static final String TRIGGER = "syncPerson.personEvents";
   private static volatile boolean failSync;


   public static void define(QInstance instance) throws QException
   {
      // Require production sample wiring; registering it here would conceal a
      // stock sample integration defect and invalidate acceptance evidence.
      if(instance.getApp("esb") == null || instance.getWidget(EsbOverviewWidgetMetaDataProducer.NAME) == null)
      {
         throw new QException("The sample JAR must register its ESB app and overview widget");
      }
      for(String name : List.of("esbPauseTrigger", "esbResumeTrigger", "esbRestartTrigger", "esbReplayDeadLetters",
         "esbPauseQueue", "esbResumeQueue", "esbMoveMessages", "esbPurgeQueue", "esbDeleteMessages"))
      {
         if(instance.getProcess(name) == null)
         {
            throw new QException("The sample JAR must register its ESB process " + name);
         }
      }
      List<QCodeReference> routes = QJavalinMetaData.ofOrWithNew(instance).getAdditionalRouteProviderReferences();
      if(routes == null || routes.stream().noneMatch(route -> EsbRouteProvider.class.getName().equals(route.getName())))
      {
         throw new QException("The sample JAR must register EsbRouteProvider");
      }
      QBackendStepMetaData step = (QBackendStepMetaData) instance.getProcess("syncPerson").getStep("sync");
      step.setCode(new QCodeReference(ReceiptStep.class));
      EsbProcessMetaData.of(instance.getProcess("syncPerson")).getTriggers().get(0).setMaxAttempts(1);
   }


   public static void prime(Connection connection) throws Exception
   {
      failSync = false;
      try(Statement statement = connection.createStatement())
      {
         statement.execute("DROP TABLE IF EXISTS acceptance_esb_receipt");
         statement.execute("CREATE TABLE acceptance_esb_receipt (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, subject VARCHAR(100), event_type VARCHAR(200), first_name VARCHAR(200))");
      }
   }


   public static void setFailure(boolean fail)
   {
      failSync = fail;
   }


   /*******************************************************************************
    ** Read the actual owned subscription's broker state. A PAUSED runner can
    ** still be finishing its outstanding receive; tests wait for zero consumers
    ** before publishing the message they require to remain on the broker.
    *******************************************************************************/
   public static Map<String, Long> subscriptionState(QInstance instance) throws Exception
   {
      QContext.init(instance, new QSession());
      String subscription = EsbBrokerNames.subscriptionQueue(EsbProviderType.ACTIVEMQ_ARTEMIS, "personEvents", TRIGGER);
      String queueName = subscription.substring(subscription.indexOf("::") + 2);
      Map<String, Long> state = new java.util.LinkedHashMap<>();
      try(Session session = EsbConnectionManager.getInstance().openSession(PROVIDER, false))
      {
         TemporaryQueue replies = session.createTemporaryQueue();
         try(MessageConsumer consumer = session.createConsumer(replies);
             MessageProducer producer = session.createProducer(session.createQueue("activemq.management")))
         {
            for(String attribute : List.of("consumerCount", "deliveringCount", "messageCount"))
            {
               Message request = session.createMessage();
               JMSManagementHelper.putAttribute(request, ResourceNames.QUEUE + queueName, attribute);
               request.setJMSReplyTo(replies);
               producer.send(request);
               Message reply = consumer.receive(5000);
               if(reply == null || !JMSManagementHelper.hasOperationSucceeded(reply))
               {
                  throw new IllegalStateException("Could not read owned subscription " + attribute);
               }
               state.put(attribute, ((Number) JMSManagementHelper.getResult(reply)).longValue());
            }
         }
         finally
         {
            replies.delete();
         }
      }
      return state;
   }


   /*******************************************************************************
    ** Stop first so no subscriber can race H2 reseeding or leave a delivery in
    ** flight. Drain only this fixture's queues; never touch unrelated brokers.
    *******************************************************************************/
   public static void stopAndDrain(QInstance instance) throws Exception
   {
      QEsbRuntime runtime = QEsbRuntime.getInstance();
      runtime.stop();
      if(runtime.getRunners().stream().anyMatch(runner -> runner.getState() != EsbTriggerState.STOPPED))
      {
         throw new IllegalStateException("ESB consumers did not stop before acceptance reset");
      }
      QContext.init(instance, new QSession());
      try(Session session = EsbConnectionManager.getInstance().openSession(PROVIDER, true))
      {
         String subscription = EsbBrokerNames.subscriptionQueue(EsbProviderType.ACTIVEMQ_ARTEMIS, "personEvents", TRIGGER);
         for(String name : List.of(subscription, "personEvents." + TRIGGER + ".dlq"))
         {
            try(MessageConsumer consumer = session.createConsumer(EsbConnectionManager.getInstance().resolveQueue(session, PROVIDER, name)))
            {
               resumeQueue(name);
               int count = 0;
               while(consumer.receive(100) != null)
               {
                  session.commit();
                  if(++count > 10000)
                  {
                     throw new IllegalStateException("Acceptance queue drain exceeded its bound: " + name);
                  }
               }
               session.commit();
            }
         }
      }
      EsbConnectionManager.getInstance().closeAll();
      EsbStats.getInstance().reset();
      failSync = false;
   }


   /*******************************************************************************
    ** Reset uses Artemis's real management-message API (no HTTP adapter or mock).
    ** Queue consumers are created before this call so an empty DLQ exists too.
    *******************************************************************************/
   private static void resumeQueue(String brokerName) throws Exception
   {
      String queueName = brokerName.contains("::") ? brokerName.substring(brokerName.indexOf("::") + 2) : brokerName;
      try(Session session = EsbConnectionManager.getInstance().openSession(PROVIDER, false))
      {
         TemporaryQueue replies = session.createTemporaryQueue();
         try(MessageConsumer consumer = session.createConsumer(replies);
             MessageProducer producer = session.createProducer(session.createQueue("activemq.management")))
         {
            Message request = session.createMessage();
            JMSManagementHelper.putOperationInvocation(request, ResourceNames.QUEUE + queueName, "resume");
            request.setJMSReplyTo(replies);
            producer.send(request);
            Message reply = consumer.receive(5000);
            if(reply == null || !JMSManagementHelper.hasOperationSucceeded(reply))
            {
               throw new IllegalStateException("Could not resume owned acceptance queue " + queueName + ": " +
                  (reply == null ? "management response timed out" : JMSManagementHelper.getResult(reply)));
            }
         }
         finally
         {
            replies.delete();
         }
      }
   }


   public static void start(QInstance instance) throws Exception
   {
      QEsbRuntime runtime = QEsbRuntime.getInstance();
      runtime.start(instance);
      awaitReady();
   }


   public static void awaitReady() throws Exception
   {
      QEsbRuntime runtime = QEsbRuntime.getInstance();
      long deadline = System.nanoTime() + java.util.concurrent.TimeUnit.SECONDS.toNanos(15);
      while(!runtime.isRunning() || runtime.getRunner(TRIGGER).getState() != EsbTriggerState.RUNNING)
      {
         if(System.nanoTime() >= deadline)
         {
            throw new IllegalStateException("Sample ESB trigger/control subscription was not ready within 15 seconds");
         }
         Thread.sleep(25);
      }
   }


   public static class ReceiptStep extends SyncPersonStep
   {
      @Override
      public void run(RunBackendStepInput input, RunBackendStepOutput output) throws QException
      {
         if(failSync)
         {
            throw new QException("Owned acceptance sync failure");
         }
         super.run(input, output);
         @SuppressWarnings("unchecked")
         List<EsbEvent> events = (List<EsbEvent>) input.getValue("esbMessages");
         try(Connection connection = ConnectionManager.getConnection(SampleMetaDataProvider.defineRdbmsBackend());
             PreparedStatement statement = connection.prepareStatement("INSERT INTO acceptance_esb_receipt (subject, event_type, first_name) VALUES (?, ?, ?)"))
         {
            for(EsbEvent event : events)
            {
               Map<?, ?> values = (Map<?, ?>) event.getData().get("record");
               statement.setString(1, event.getSubject());
               statement.setString(2, event.getType());
               statement.setString(3, values == null ? null : String.valueOf(values.get("firstName")));
               statement.executeUpdate();
            }
         }
         catch(Exception e)
         {
            throw new QException("Failed to record the owned subscriber effect", e);
         }
      }
   }
}
