/*
 * Copyright 2026 QRun.IO, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Entry point of the standalone (container image) dashboard: runs the Next standalone
 * server (`server.js`, generated by `next build` next to this file) with the security headers
 * the QQQ server sends with the export it hosts (QRun-IO/qqq#734, see security-headers.mjs).
 *
 * The identity provider origin comes from the backend's `GET /qqq/v1/metaData/authentication`
 * (read through this server's own API rewrites). Other origins the dashboard must reach (a
 * QuickSight embed, custom component bundles, image or media hosts) are added with
 * `QQQ_DASHBOARD_CSP_SOURCES`, for example
 * `frame-src https://*.quicksight.aws.amazon.com; script-src https://cdn.example.com`.
 */

import http from 'node:http'
import { createRequire } from 'node:module'
import {
  applyDashboardSecurityHeaders,
  buildContentSecurityPolicy,
  createIdentityProviderOrigins,
  isBackendPath,
  parseSourceAdditions,
} from './security-headers.mjs'

const additions = parseSourceAdditions(process.env.QQQ_DASHBOARD_CSP_SOURCES)
const port = parseInt(process.env.PORT ?? '', 10) || 3000
const listenHost = process.env.HOSTNAME || '0.0.0.0'
const selfHost = ['0.0.0.0', '::', ''].includes(listenHost) ? '127.0.0.1' : listenHost.includes(':') ? `[${listenHost}]` : listenHost
const identityProviderOrigins = createIdentityProviderOrigins(async () => {
  const response = await fetch(`http://${selfHost}:${port}/qqq/v1/metaData/authentication`, { signal: AbortSignal.timeout(5_000) })
  if (!response.ok) throw new Error(`GET /qqq/v1/metaData/authentication answered ${response.status}`)
  return response.json()
})

// server.js creates one HTTP server; its request listener is wrapped to add the headers
const createServer = http.createServer
http.createServer = function (...args) {
  http.createServer = createServer
  const index = args.findIndex((argument) => typeof argument === 'function')
  if (index < 0) throw new Error('The Next standalone server created its HTTP server without a request listener; the dashboard security headers cannot be added.')
  const listener = args[index]
  args[index] = async function (req, res) {
    if (!isBackendPath(req.url ?? '/')) {
      const connectOrigins = await identityProviderOrigins()
      applyDashboardSecurityHeaders(req, res, (scriptHashes) => buildContentSecurityPolicy({ connectOrigins, additions, scriptHashes }))
    }
    return listener.call(this, req, res)
  }
  return createServer.apply(this, args)
}

createRequire(import.meta.url)('./server.js')
