/*
 * Copyright 2026 QRun.IO, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file Entry point of the standalone (container image) dashboard: runs the Next standalone
 * server (`server.js`, generated by `next build` next to this file) with the security headers
 * the QQQ server sends with the export it hosts (QRun-IO/qqq#734, see security-headers.mjs).
 *
 * Identity provider and application CSP sources come from the backend's
 * `GET /qqq/v1/metaData/authentication`, through this server's own API rewrites.
 * Additional operator-owned sources (or application sources on older backends) use
 * `QQQ_DASHBOARD_CSP_SOURCES`, for example `img-src https://images.example.com`.
 */

import http from 'node:http'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { createBrandingAssetAlias } from './branding-assets.mjs'
import {
  applyDashboardSecurityHeaders,
  buildContentSecurityPolicy,
  createDashboardPolicyInputs,
  isBackendPath,
  parseSourceAdditions,
} from './security-headers.mjs'

const additions = parseSourceAdditions(process.env.QQQ_DASHBOARD_CSP_SOURCES)
const port = parseInt(process.env.PORT ?? '', 10) || 3000
const listenHost = process.env.HOSTNAME || '0.0.0.0'
const selfHost = ['0.0.0.0', '::', ''].includes(listenHost) ? '127.0.0.1' : listenHost.includes(':') ? `[${listenHost}]` : listenHost
const dashboardPolicyInputs = createDashboardPolicyInputs(async () => {
  const response = await fetch(`http://${selfHost}:${port}/qqq/v1/metaData/authentication`, { signal: AbortSignal.timeout(5_000) })
  if (!response.ok) throw new Error(`GET /qqq/v1/metaData/authentication answered ${response.status}`)
  return response.json()
})

// These two fields are already public before sign-in. The fixed role endpoint requires
// a backend containing QQQ #1009; old backends retain their real 404, never a fallback UI.
const brandingAlias = createBrandingAssetAlias(async () => {
  const response = await fetch(`http://${selfHost}:${port}/qqq/v1/metaData/authentication`, { signal: AbortSignal.timeout(5_000) })
  if (!response.ok) throw new Error('Could not load public branding metadata')
  return response.json()
}, fileURLToPath(new URL('./public', import.meta.url)))

// server.js creates one HTTP server; its request listener is wrapped to add the headers
const createServer = http.createServer
http.createServer = function (...args) {
  http.createServer = createServer
  const index = args.findIndex((argument) => typeof argument === 'function')
  if (index < 0) throw new Error('The Next standalone server created its HTTP server without a request listener; the dashboard security headers cannot be added.')
  const listener = args[index]
  args[index] = async function (req, res) {
    const asset = await brandingAlias(req.method, req.url ?? '/')
    if (asset) req.url = asset
    if (!isBackendPath(req.url ?? '/')) {
      const policyInputs = await dashboardPolicyInputs()
      applyDashboardSecurityHeaders(req, res, (scriptHashes) => buildContentSecurityPolicy({ ...policyInputs, additions, scriptHashes }))
    }
    return listener.call(this, req, res)
  }
  return createServer.apply(this, args)
}

createRequire(import.meta.url)('./server.js')
