// QQQ Enum Types - ported from qqq-frontend-core

export type QFieldType =
  | 'STRING'
  | 'INTEGER'
  | 'LONG'
  | 'DECIMAL'
  | 'BOOLEAN'
  | 'DATE'
  | 'TIME'
  | 'DATE_TIME'
  | 'TEXT'
  | 'HTML'
  | 'PASSWORD'
  | 'BLOB'

export type QAppNodeType = 'TABLE' | 'PROCESS' | 'REPORT' | 'APP'

export type Capability =
  | 'TABLE_QUERY'
  | 'TABLE_GET'
  | 'TABLE_COUNT'
  | 'TABLE_INSERT'
  | 'TABLE_UPDATE'
  | 'TABLE_DELETE'

export type QCriteriaOperator =
  | 'EQUALS'
  | 'NOT_EQUALS'
  | 'NOT_EQUALS_OR_IS_NULL'
  | 'IN'
  | 'NOT_IN'
  | 'STARTS_WITH'
  | 'ENDS_WITH'
  | 'CONTAINS'
  | 'NOT_STARTS_WITH'
  | 'NOT_ENDS_WITH'
  | 'NOT_CONTAINS'
  | 'LESS_THAN'
  | 'LESS_THAN_OR_EQUALS'
  | 'GREATER_THAN'
  | 'GREATER_THAN_OR_EQUALS'
  | 'IS_BLANK'
  | 'IS_NOT_BLANK'
  | 'BETWEEN'
  | 'NOT_BETWEEN'

export type QComponentType =
  | 'HELP_TEXT'
  | 'BULK_EDIT_FORM'
  | 'BULK_LOAD_FILE_MAPPING_FORM'
  | 'BULK_LOAD_VALUE_MAPPING_FORM'
  | 'BULK_LOAD_PROFILE_FORM'
  | 'VALIDATION_REVIEW_SCREEN'
  | 'EDIT_FORM'
  | 'VIEW_FORM'
  | 'DOWNLOAD_FORM'
  | 'RECORD_LIST'
  | 'PROCESS_SUMMARY_RESULTS'
  | 'GOOGLE_DRIVE_SELECT_FOLDER'
  | 'WIDGET'
  | 'HTML'

export type AdornmentType =
  | 'LINK'
  | 'CHIP'
  | 'SIZE'
  | 'ERROR'
  | 'RENDER_HTML'
  | 'REVEAL'
  | 'CODE_EDITOR'
  | 'FILE_DOWNLOAD'
  | 'FILE_UPLOAD'
  | 'TOOLTIP'
